#!/usr/bin/env sh

set -ex -o pipefail

#cat x.x | ./x x.x
cat xc.ll > /tmp/out.ll && ./scm xc.x < check.x >> /tmp/out.ll
clang -Wno-override-module -lgc -L/usr/local/lib /tmp/out.ll -o /tmp/exe && /tmp/exe

