#!/usr/bin/env bash

set -e -o pipefail

trap 'echo "FAIL: Command failed with exit code $?"' ERR

# compile
c() {
  comp=$1
  base=$(basename $2 .x)
  cat xc.ll > /tmp/$base.ll && cat std.x $2 | $comp >> /tmp/$base.ll
  clang -Wno-override-module -lgc /tmp/$base.ll -o /tmp/$base
}

date > /tmp/log

echo "verify ( s | xi | check ) passes..."
./scm x.x < <(cat std.x check.x) 2>&1 >> /tmp/log

echo "verify ( s | xc | check ) passes..."
c "./scm xc.x" check.x 2>&1 >> /tmp/log
/tmp/check 2>&1 >> /tmp/log

echo "verify ( s | xc | xi = XI ) finishes..."
c "./scm xc.x" x.x 2>&1 >> /tmp/log

echo "verify ( XI | check ) passes..."
/tmp/x < <(cat std.x check.x) 2>&1 >> /tmp/log

echo "verify ( s | xc | xc = XC) finishes..."
c "./scm xc.x" xc.x 2>&1 >> /tmp/log
mv /tmp/xc /tmp/xc1

echo "verify ( XC | check ) passes -- compiler!..."
c /tmp/xc1 check.x 2>&1 >> /tmp/log
/tmp/check 2>&1 >> /tmp/log

echo "verify ( XC | xi | check ) passes -- REPL!..."
c /tmp/xc1 x.x 2>&1 >> /tmp/log
/tmp/x < <(cat std.x check.x) 2>&1 >> /tmp/log

echo "verify ( XC | xi | xi | check ) passes -- nested REPLs!..."
cat std.x x.x check.x | /tmp/x 2>&1 >> /tmp/log

echo "verify ( XC | xc = XC ) -- fixed point!..."
c /tmp/xc1 xc.x 2>&1 >> /tmp/log
mv /tmp/xc /tmp/xc2
[ "$(md5 -q /tmp/xc1)" = "$(md5 -q /tmp/xc2)" ]

echo "Verify ( XC | eo ) passes -- TCO!..."
c /tmp/xc1 eo.x 2>&1 >> /tmp/log
/tmp/eo 2>&1 >> /tmp/log

echo "PASS"

