(define a 1)
(define b a)
(set! b 2)
(pretty-print a)
(newline)
(pretty-print b)
(newline)
(define get-first-a (lambda () a))
(define a 3)
(pretty-print (get-first-a))
(newline)
(pretty-print a)
(newline)
