#!/usr/bin/env bash

## Check binary equality (black box)
# C = Scc = Icc = Cc
# I = Sci = Ici = Ci
# T = Sct = Ict = Ct

## Check output equality (glass box)
# St = It = Ct

set -eE -o pipefail

trap 'echo FAIL' ERR

eq() {
  [ "$(md5 -q $1)" = "$(md5 -q $2)" ]
}

build() {
  /usr/bin/time $2 < <(cat $3 $4) > $1
  chmod +x $1
}

# Bootstrap C
echo "C := Scc"
build /tmp/xc1 ./xs xc.x xc.x

# Bootstrap I
echo "I := Sci"
build /tmp/xi1 ./xs xc.x xi.x

# C = Cc
echo "C == Cc"
build /tmp/xc2 /tmp/xc1 xc.x
eq /tmp/xc1 /tmp/xc2

# C = Icc
echo "C == Icc"
build /tmp/xc3 /tmp/xi1 xc.x xc.x
eq /tmp/xc1 /tmp/xc3

# I = Ci
echo "I == Ci"
build /tmp/xi2 /tmp/xc1 xi.x
eq /tmp/xi1 /tmp/xi2

# I = Ici
echo "I == Ici"
build /tmp/xi3 /tmp/xi1 xc.x xi.x
eq /tmp/xi1 /tmp/xi3

# T = St
echo "T := St"
build /tmp/t1 ./xs test.x

# T = It
echo "T == It"
build /tmp/t2 /tmp/xi1 test.x
eq /tmp/t1 /tmp/t2

# T = Ct
echo "T == Ct"
build /tmp/t3 /tmp/xc1 test.x
eq /tmp/t1 /tmp/t3

echo PASS

