#!/usr/bin/env bash

## Check binary equality (black box)
# C = Scc = Icc = Cc
# I = Sci = Ici = Ci
# T = Sct = Ict = Ct

## Check output equality (glass box)
# St = It = Ct

set -e -o pipefail

c() {
  comp=$1
  base=$(basename $2 .x)
  cat xc.ll > /tmp/$base.ll && cat std.x $2 | $comp >> /tmp/$base.ll
  clang -Wno-override-module -lgc /tmp/$base.ll -o /tmp/$base
}

eq() {
  [ "$(md5 -q $1)" = "$(md5 -q $2)" ] || { echo "FAIL: NOT EQUAL"; exit 1; }
}

# Bootstrap C
echo "C := Scc"
./xs < <(cat xc.x xc.x) > /tmp/xc1

# Bootstrap I
echo "I := Sci"
./xs < <(cat xc.x xi.x) > /tmp/xi1

# C = Cc
echo "C == Cc"
/tmp/xc1 < xc.x > /tmp/xc2
eq /tmp/xc1 /tmp/xc2

# C = Icc
echo "C == Icc"
/tmp/xi1 < <(cat xc.x xc.x) > /tmp/xc3
eq /tmp/xc1 /tmp/xc3

# I = Ci
echo "I == Ci"
/tmp/xc1 < xi.x > /tmp/xi2
eq /tmp/xi1 /tmp/xi2

# I = Ici
echo "I == Ici"
/tmp/xi1 < <(cat xc.x xi.x) > /tmp/xi3
eq /tmp/xi1 /tmp/xi3

# T = St
echo "T := St"
./xs < test.x | tee /tmp/t1

# T = It
echo "T == It"
/tmp/xi1 < test.x | tee /tmp/t2
eq /tmp/t1 /tmp/t2

# T = Ct
echo "T == Ct"
/tmp/xc1 < test.x | tee /tmp/t3
eq /tmp/t1 /tmp/t3

echo PASS
